apiVersion: v1
kind: ConfigMap

metadata:
  name: api
  namespace: default

data:
  config.yml: |
    mongo:
      host: mongo
      port: "21871"
      db: self
      user: robot

    airtable:
      baseId: appDm0Ts20KbQ0rG0
      moodSource:
        limit: 10

    jobserver:
      redisAddr: redis-master:6379
      fetchMoodsCron: 0 0-59/5 * * * *
