apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: api
  namespace: default

data:
  AIRTABLE_API_KEY: a2V5MEFWb2gwb3ZoV0xxR3I=
  MONGO_PASS: Y2x1c3RlcnRydWNrOQ==
  POSTGRES_PASS: Y2x1c3RlcnRydWNrOA==

