name: build-test
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate server tags
        id: generate-server-tags
        uses: stevenxie/generate-docker-tags-action@v0.2.1
        with:
          repo: stevenxie/api-server
      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/server.Dockerfile
          push: true
          tags: ${{ steps.generate-server-tags.outputs.tags }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache,mode=max
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: Swatinem/rust-cache@v1.0.1
      - name: Lint
        run: cargo clippy && cargo fmt -- --check
      - name: Test
        run: cargo test
