name: push
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: Swatinem/rust-cache@v1.0.1
      - name: Test
        run: cargo test
      - name: Lint
        run: cargo clippy && cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: stevenxie/api
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
